export type Belt = {
  id: string;
  name: string;
  leather: string;
  color: string;
  price: number;
  sizes: string[];
  inStock: boolean;
  image: string;
  description: string;
  buckle: string;
  gradientFrom: string;
  gradientTo: string;
};

export const belts: Belt[] = [
  {
    id: "himalayan-croc-belt",
    name: "Himalayan Crocodile",
    leather: "Crocodile",
    color: "Himalayan White Grey",
    price: 1800,
    sizes: ["32", "34", "36", "38", "40", "42"],
    inStock: true,
    image: "/images/belts/placeholder.jpg",
    description: "Himalayan crocodile leather with interchangeable buckle system. The rarest belt in the collection.",
    buckle: "Interchangeable System",
    gradientFrom: "#D4CFC8",
    gradientTo: "#8A8580",
  },
  {
    id: "stingray-navy",
    name: "Caviar Stingray",
    leather: "Stingray",
    color: "Navy Caviar",
    price: 850,
    sizes: ["30", "36"],
    inStock: true,
    image: "/images/belts/placeholder.jpg",
    description: "Caviar stingray leather belt strap. Virtually indestructible.",
    buckle: "Chrome Oval Cross",
    gradientFrom: "#1A2A4A",
    gradientTo: "#0D1829",
  },
  {
    id: "stingray-black",
    name: "Caviar Stingray",
    leather: "Stingray",
    color: "Black Caviar",
    price: 875,
    sizes: ["31"],
    inStock: true,
    image: "/images/belts/placeholder.jpg",
    description: "Black caviar stingray leather belt strap.",
    buckle: "Chrome Oval Cross",
    gradientFrom: "#2A2A2A",
    gradientTo: "#0A0A0A",
  },
  {
    id: "stingray-charcoal",
    name: "Caviar Stingray",
    leather: "Stingray",
    color: "Charcoal Caviar",
    price: 850,
    sizes: ["30"],
    inStock: true,
    image: "/images/belts/placeholder.jpg",
    description: "Charcoal caviar stingray belt strap.",
    buckle: "Chrome Oval Cross",
    gradientFrom: "#3D3D3D",
    gradientTo: "#1A1A1A",
  },
  {
    id: "croc-grey",
    name: "Grey Crocodile",
    leather: "Crocodile",
    color: "Ash Grey",
    price: 850,
    sizes: ["30", "33", "36", "42"],
    inStock: true,
    image: "/images/belts/placeholder.jpg",
    description: "Grey crocodile leather belt strap.",
    buckle: "Chrome Cross",
    gradientFrom: "#6B6B6B",
    gradientTo: "#3A3A3A",
  },
  {
    id: "croc-black",
    name: "Bone Crocodile",
    leather: "Crocodile",
    color: "Black",
    price: 595,
    sizes: ["38", "40"],
    inStock: true,
    image: "/images/belts/placeholder.jpg",
    description: "Black bone crocodile leather belt.",
    buckle: "Sterling Silver",
    gradientFrom: "#1F1F1F",
    gradientTo: "#0A0A0A",
  },
  {
    id: "croc-navy",
    name: "Bone Crocodile",
    leather: "Crocodile",
    color: "Deep Navy",
    price: 595,
    sizes: ["30", "36"],
    inStock: true,
    image: "/images/belts/placeholder.jpg",
    description: "Navy blue hornback crocodile leather belt.",
    buckle: "Sterling Silver",
    gradientFrom: "#1A2035",
    gradientTo: "#0A0F1C",
  },
  {
    id: "croc-taupe",
    name: "Bone Crocodile",
    leather: "Crocodile",
    color: "Taupe Grey",
    price: 595,
    sizes: ["34", "38"],
    inStock: true,
    image: "/images/belts/placeholder.jpg",
    description: "Taupe grey bone crocodile leather belt.",
    buckle: "Sterling Silver",
    gradientFrom: "#8C8075",
    gradientTo: "#5C5248",
  },
  {
    id: "croc-olive",
    name: "Bone Crocodile",
    leather: "Crocodile",
    color: "Olive Green",
    price: 595,
    sizes: ["36"],
    inStock: true,
    image: "/images/belts/placeholder.jpg",
    description: "Olive green bone crocodile leather belt.",
    buckle: "Sterling Silver",
    gradientFrom: "#4A4E2A",
    gradientTo: "#2A2E10",
  },
  {
    id: "croc-purple",
    name: "Bone Crocodile",
    leather: "Crocodile",
    color: "Purple",
    price: 595,
    sizes: ["34"],
    inStock: true,
    image: "/images/belts/placeholder.jpg",
    description: "Purple bone crocodile leather belt.",
    buckle: "Sterling Silver",
    gradientFrom: "#4A2A5C",
    gradientTo: "#2A1035",
  },
  {
    id: "calf-hair-bw",
    name: "Calf Hair Animal Print",
    leather: "Calf Hair",
    color: "Black/White",
    price: 650,
    sizes: ["30", "33", "38", "42"],
    inStock: true,
    image: "/images/belts/placeholder.jpg",
    description: "Animal print calf hair leather belt strap.",
    buckle: "Cemetery Cross",
    gradientFrom: "#3A3A3A",
    gradientTo: "#F5F0EB",
  },
  {
    id: "calf-hair-leopard",
    name: "Leopard Calf Hair",
    leather: "Calf Hair",
    color: "Leopard Print",
    price: 650,
    sizes: ["32", "34", "40", "42"],
    inStock: true,
    image: "/images/belts/placeholder.jpg",
    description: "Leopard print calf hair leather belt strap.",
    buckle: "Cemetery Cross",
    gradientFrom: "#8C6A2A",
    gradientTo: "#3A2A10",
  },
  {
    id: "croc-orange",
    name: "Orange Crocodile",
    leather: "Crocodile",
    color: "Orange",
    price: 850,
    sizes: ["34"],
    inStock: false,
    image: "/images/belts/placeholder.jpg",
    description: "Orange crocodile leather belt strap.",
    buckle: "Chrome Cross",
    gradientFrom: "#8C3A0A",
    gradientTo: "#4A1E05",
  },
  {
    id: "croc-blue",
    name: "Blue Crocodile",
    leather: "Crocodile",
    color: "Royal Blue",
    price: 850,
    sizes: ["32"],
    inStock: false,
    image: "/images/belts/placeholder.jpg",
    description: "Blue crocodile leather belt strap.",
    buckle: "Chrome Cross",
    gradientFrom: "#1A3A7A",
    gradientTo: "#0A1A40",
  },
  {
    id: "zebra-calf",
    name: "Zebra Calf Hair",
    leather: "Calf Hair",
    color: "Zebra Print",
    price: 650,
    sizes: ["36"],
    inStock: false,
    image: "/images/belts/placeholder.jpg",
    description: "Zebra print calf hair belt with buckle system.",
    buckle: "Interchangeable System",
    gradientFrom: "#D4D4D4",
    gradientTo: "#1A1A1A",
  },
];
