// TODO: Replace static product data with Shopify Storefront API
// Products will be fetched via GraphQL from Shopify
// This static data mirrors the Shopify product schema for easy migration
// See: https://shopify.dev/docs/api/storefront

export type Product = {
  id: string;
  name: string;
  category: "Belts" | "Belt Straps" | "Belt Buckles" | "Wallets" | "Bags";
  subcategory: string;
  price: number;
  comparePrice?: number;
  leather: string;
  color: string;
  sizes: string[];
  images: string[];
  inStock: boolean;
  isNew: boolean;
  description: string;
  tags: string[];
};

export const products: Product[] = [
  // ── In Stock ────────────────────────────────────────────────────────────────
  {
    id: "stingray-belt-navy-36",
    name: "Exotic Caviar Stingray Belt Strap",
    category: "Belt Straps",
    subcategory: "Exotic",
    price: 850,
    leather: "Stingray",
    color: "Navy Caviar",
    sizes: ["36"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: true,
    isNew: true,
    description: "Caviar stingray leather belt strap, handcrafted in Italy.",
    tags: ["exotic", "stingray", "new"],
  },
  {
    id: "car-buckle-blue",
    name: "Vintage Car Belt Buckle — Hand Painted 1/1",
    category: "Belt Buckles",
    subcategory: "Art Pieces",
    price: 400,
    leather: "N/A",
    color: "Blue",
    sizes: ["OS"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: true,
    isNew: true,
    description: "One-of-one hand painted vintage car belt buckle.",
    tags: ["buckle", "hand-painted", "1of1", "new"],
  },
  {
    id: "stingray-belt-black-31",
    name: "Exotic Caviar Stingray Belt Strap",
    category: "Belt Straps",
    subcategory: "Exotic",
    price: 875,
    leather: "Stingray",
    color: "Black Caviar",
    sizes: ["31"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: true,
    isNew: true,
    description: "Black caviar stingray leather belt strap.",
    tags: ["exotic", "stingray", "new"],
  },
  {
    id: "croc-belt-grey",
    name: "Exotic Grey Crocodile Belt Strap",
    category: "Belt Straps",
    subcategory: "Exotic",
    price: 850,
    leather: "Crocodile",
    color: "Ash Grey",
    sizes: ["30", "33", "36", "42"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: true,
    isNew: true,
    description: "Grey crocodile leather belt strap.",
    tags: ["exotic", "crocodile", "new"],
  },
  {
    id: "calf-hair-bw",
    name: "Calf Hair Belt Strap — Animal Print",
    category: "Belt Straps",
    subcategory: "Calf Hair",
    price: 650,
    leather: "Calf Hair",
    color: "Black/White",
    sizes: ["30", "33", "38", "42"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: true,
    isNew: false,
    description: "Animal print calf hair leather belt strap.",
    tags: ["calf-hair", "animal-print"],
  },
  {
    id: "stingray-belt-charcoal",
    name: "Exotic Caviar Stingray Belt Strap",
    category: "Belt Straps",
    subcategory: "Exotic",
    price: 850,
    leather: "Stingray",
    color: "Charcoal Caviar",
    sizes: ["30"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: true,
    isNew: false,
    description: "Charcoal caviar stingray belt strap.",
    tags: ["exotic", "stingray"],
  },
  {
    id: "calf-hair-leopard-sm",
    name: "Leopard Print Calf Hair Belt Strap",
    category: "Belt Straps",
    subcategory: "Calf Hair",
    price: 650,
    leather: "Calf Hair",
    color: "Leopard Print",
    sizes: ["32-34"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: true,
    isNew: false,
    description: "Leopard print calf hair belt strap.",
    tags: ["calf-hair", "animal-print", "leopard"],
  },
  {
    id: "calf-hair-leopard-lg",
    name: "Leopard Print Calf Hair Belt Strap",
    category: "Belt Straps",
    subcategory: "Calf Hair",
    price: 650,
    leather: "Calf Hair",
    color: "Leopard Print",
    sizes: ["40-42"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: true,
    isNew: false,
    description: "Leopard print calf hair belt strap.",
    tags: ["calf-hair", "animal-print", "leopard"],
  },
  {
    id: "himalayan-croc-34-36",
    name: "Himalayan Crocodile Belt — Buckle System",
    category: "Belts",
    subcategory: "Himalayan",
    price: 1800,
    leather: "Crocodile",
    color: "Himalayan White Grey",
    sizes: ["100cm (US 34-36)"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: true,
    isNew: false,
    description: "Himalayan crocodile leather belt with interchangeable buckle system.",
    tags: ["exotic", "crocodile", "himalayan", "premium"],
  },
  {
    id: "himalayan-croc-38-40",
    name: "Himalayan Crocodile Belt — Buckle System",
    category: "Belts",
    subcategory: "Himalayan",
    price: 1800,
    leather: "Crocodile",
    color: "Himalayan White Grey",
    sizes: ["110cm (38-40)"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: true,
    isNew: false,
    description: "Himalayan crocodile leather belt with interchangeable buckle system.",
    tags: ["exotic", "crocodile", "himalayan", "premium"],
  },
  {
    id: "himalayan-croc-32-34",
    name: "Himalayan Crocodile Belt — Buckle System",
    category: "Belts",
    subcategory: "Himalayan",
    price: 1800,
    leather: "Crocodile",
    color: "Himalayan White Grey",
    sizes: ["95cm (32-34)"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: true,
    isNew: false,
    description: "Himalayan crocodile leather belt with interchangeable buckle system.",
    tags: ["exotic", "crocodile", "himalayan", "premium"],
  },
  {
    id: "himalayan-croc-40-42",
    name: "Himalayan Crocodile Belt — Buckle System",
    category: "Belts",
    subcategory: "Himalayan",
    price: 1800,
    leather: "Crocodile",
    color: "Himalayan White Grey",
    sizes: ["115cm (40-42)"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: true,
    isNew: false,
    description: "Himalayan crocodile leather belt with interchangeable buckle system.",
    tags: ["exotic", "crocodile", "himalayan", "premium"],
  },
  {
    id: "bone-croc-black",
    name: "Bone Crocodile Belt",
    category: "Belts",
    subcategory: "Crocodile",
    price: 595,
    leather: "Crocodile",
    color: "Black",
    sizes: ["38", "40"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: true,
    isNew: false,
    description: "Bone crocodile leather belt.",
    tags: ["exotic", "crocodile"],
  },
  {
    id: "bone-croc-navy",
    name: "Bone Crocodile Belt",
    category: "Belts",
    subcategory: "Crocodile",
    price: 595,
    leather: "Crocodile",
    color: "Deep Navy Blue",
    sizes: ["30", "36"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: true,
    isNew: false,
    description: "Navy blue hornback crocodile leather belt.",
    tags: ["exotic", "crocodile"],
  },
  {
    id: "ostrich-wallet",
    name: "Ostrich Bifold Wallet",
    category: "Wallets",
    subcategory: "Bifold",
    price: 325,
    leather: "Ostrich",
    color: "Chocolate Brown",
    sizes: ["OS"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: true,
    isNew: false,
    description: "Brown ostrich leather bifold wallet.",
    tags: ["exotic", "ostrich", "wallet"],
  },
  {
    id: "bone-croc-taupe",
    name: "Bone Crocodile Belt",
    category: "Belts",
    subcategory: "Crocodile",
    price: 595,
    leather: "Crocodile",
    color: "Taupe Grey",
    sizes: ["34", "38"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: true,
    isNew: false,
    description: "Taupe grey bone crocodile leather belt.",
    tags: ["exotic", "crocodile"],
  },
  {
    id: "bone-croc-olive",
    name: "Bone Crocodile Belt",
    category: "Belts",
    subcategory: "Crocodile",
    price: 595,
    leather: "Crocodile",
    color: "Olive Green",
    sizes: ["36"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: true,
    isNew: false,
    description: "Olive green bone crocodile leather belt.",
    tags: ["exotic", "crocodile"],
  },
  {
    id: "bone-croc-purple",
    name: "Bone Crocodile Belt",
    category: "Belts",
    subcategory: "Crocodile",
    price: 595,
    leather: "Crocodile",
    color: "Purple",
    sizes: ["34"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: true,
    isNew: false,
    description: "Purple bone crocodile leather belt.",
    tags: ["exotic", "crocodile"],
  },
  // ── Sold Out ────────────────────────────────────────────────────────────────
  {
    id: "croc-belt-orange",
    name: "Exotic Orange Crocodile Belt Strap",
    category: "Belt Straps",
    subcategory: "Exotic",
    price: 850,
    leather: "Crocodile",
    color: "Orange",
    sizes: ["34", "36"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: false,
    isNew: false,
    description: "Orange crocodile leather belt strap.",
    tags: ["exotic", "crocodile"],
  },
  {
    id: "croc-belt-blue",
    name: "Exotic Blue Crocodile Belt Strap",
    category: "Belt Straps",
    subcategory: "Exotic",
    price: 850,
    leather: "Crocodile",
    color: "Cobalt Blue",
    sizes: ["32", "36"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: false,
    isNew: false,
    description: "Cobalt blue crocodile leather belt strap.",
    tags: ["exotic", "crocodile"],
  },
  {
    id: "zebra-calf-hair-belt",
    name: "Zebra Print Calf Hair Belt",
    category: "Belt Straps",
    subcategory: "Calf Hair",
    price: 650,
    leather: "Calf Hair",
    color: "Black/White Zebra",
    sizes: ["30", "34", "38"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: false,
    isNew: false,
    description: "Zebra print calf hair leather belt.",
    tags: ["calf-hair", "animal-print", "zebra"],
  },
  {
    id: "himalayan-croc-38",
    name: "Himalayan Crocodile Belt — Buckle System",
    category: "Belts",
    subcategory: "Himalayan",
    price: 1800,
    leather: "Crocodile",
    color: "Himalayan White Grey",
    sizes: ["105cm (38)"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: false,
    isNew: false,
    description: "Himalayan crocodile leather belt with interchangeable buckle system.",
    tags: ["exotic", "crocodile", "himalayan", "premium"],
  },
  {
    id: "himalayan-croc-36",
    name: "Himalayan Crocodile Belt — Buckle System",
    category: "Belts",
    subcategory: "Himalayan",
    price: 1800,
    leather: "Crocodile",
    color: "Himalayan White Grey",
    sizes: ["100cm (36)"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: false,
    isNew: false,
    description: "Himalayan crocodile leather belt with interchangeable buckle system.",
    tags: ["exotic", "crocodile", "himalayan", "premium"],
  },
  {
    id: "himalayan-croc-32",
    name: "Himalayan Crocodile Belt — Buckle System",
    category: "Belts",
    subcategory: "Himalayan",
    price: 1800,
    leather: "Crocodile",
    color: "Himalayan White Grey",
    sizes: ["90cm (32)"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: false,
    isNew: false,
    description: "Himalayan crocodile leather belt with interchangeable buckle system.",
    tags: ["exotic", "crocodile", "himalayan", "premium"],
  },
  {
    id: "himalayan-croc-90cm",
    name: "Himalayan Crocodile Belt — Buckle System",
    category: "Belts",
    subcategory: "Himalayan",
    price: 1800,
    leather: "Crocodile",
    color: "Himalayan White Grey",
    sizes: ["90cm"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: false,
    isNew: false,
    description: "Himalayan crocodile leather belt with interchangeable buckle system.",
    tags: ["exotic", "crocodile", "himalayan", "premium"],
  },
  {
    id: "stingray-card-holder",
    name: "Stingray Card Holder",
    category: "Wallets",
    subcategory: "Card Holder",
    price: 295,
    leather: "Stingray",
    color: "Black Caviar",
    sizes: ["OS"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: false,
    isNew: false,
    description: "Black caviar stingray leather card holder.",
    tags: ["exotic", "stingray", "wallet"],
  },
  {
    id: "croc-card-holder",
    name: "Crocodile Card Holder",
    category: "Wallets",
    subcategory: "Card Holder",
    price: 350,
    leather: "Crocodile",
    color: "Cognac",
    sizes: ["OS"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: false,
    isNew: false,
    description: "Cognac crocodile leather card holder.",
    tags: ["exotic", "crocodile", "wallet"],
  },
  {
    id: "ostrich-travel-wallet",
    name: "Ostrich Travel Wallet",
    category: "Wallets",
    subcategory: "Travel",
    price: 485,
    leather: "Ostrich",
    color: "Midnight Black",
    sizes: ["OS"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: false,
    isNew: false,
    description: "Midnight black ostrich leather travel wallet.",
    tags: ["exotic", "ostrich", "wallet"],
  },
  {
    id: "shark-belt-strap",
    name: "Shark Skin Belt Strap",
    category: "Belt Straps",
    subcategory: "Exotic",
    price: 750,
    leather: "Shark",
    color: "Slate Grey",
    sizes: ["32", "34", "36", "38"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: false,
    isNew: false,
    description: "Slate grey shark skin leather belt strap.",
    tags: ["exotic", "shark"],
  },
  {
    id: "python-belt-strap",
    name: "Python Belt Strap",
    category: "Belt Straps",
    subcategory: "Exotic",
    price: 695,
    leather: "Python",
    color: "Natural",
    sizes: ["32", "36", "40"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: false,
    isNew: false,
    description: "Natural python leather belt strap.",
    tags: ["exotic", "python"],
  },
  {
    id: "alligator-dress-belt",
    name: "Alligator Dress Belt",
    category: "Belts",
    subcategory: "Alligator",
    price: 895,
    leather: "Alligator",
    color: "Deep Black",
    sizes: ["32", "34", "36", "38"],
    images: ["/images/shop/placeholder.jpg"],
    inStock: false,
    isNew: false,
    description: "Deep black alligator leather dress belt.",
    tags: ["exotic", "alligator"],
  },
];
